### PR TITLE
Inclusion of shoreline contamination. Export of additional performance metrics.

### LINKED ISSUE #63: Integrate shoreline contamination flag into output rasters

### LINKED ISSUE #65: Apply QAQC bands to images prior to classification
For Landsat: Remove saturated pixels; filter out scenes whose image quality is <7

### PR DESCRIPTION
**Pull request by steeleb**
Heya!

Finally got the kinks worked out with the shoreline contamination piece (closes #63). The summary new file in here (and in the drive, `data/output/GTB_by_mission_v2023-08-03.csv`) has a new column called 'extent'. This is either 'aoi' (the entire modeling area), 'shoreline contamination' (only the area labeled shoreline contamination), or 'aoi no sc' (the modeling area less the shoreline contamination). These are all collated vertically in the dataset - so there are 3 times as many rows in this new dataset!

The code from 687 through 722 in `modeling/03_Per_Sat_Model.Rmd` closes #65 

Just a heads up: I'm going to be working on documentation, and then I'm probably going to be pretty quiet on this project until y'all need things. I'm going to start exporting the rasters for this model (I'm generally pretty happy with it - cloud/sediment/open water generally have ~ 90%  or better accuracy across the board, and unless you want better accuracy with the sed classes, I think that flies pretty well.) We can revisit the idea of using sen 2 to help elucidate plume v bloom this winter. 

More soon! 

B

### CODE REVIEW

**Comment by steeleb** [comment]
Eeep! That might be an issue in my clean up script - and if math serves me right, I think you are correct about those NA classes actually being aoi. I'll fix that right now.

Also, *something* I did (honestly not sure what) sped up the export of the rasters from hours to minutes (#62). I'm on LS8 right now and *hopefully* will have Sen-2 tomorrow. Then I can stack them. The summary stats won't change but your ability to make new AOIs and extract the data will be enabled!!

**Comment by steeleb** [comment]
Okay! Looks like that's an issue *only* with sentinel. Does that track for you? I missed one spot for adding 'extent' into the selectors and still had 'aoi' in there....

**Comment by lindsayplatt** [comment]
Yep, looks like it is only with Sentinel. No rush for the fix on my end; I was focusing on `extent == 'aoi no sc'` right now anywho

image

**Comment by steeleb** [comment]
amaze. Fixed enough for now - I updated the file in the Drive (it has the same name and same info, just with that one column filled).

**Review by lindsayplatt — APPROVED** [review]
Yay - pulled it down and all fixed. Thanks!

```
> read_csv('GTB_by_mission_v2023-08-03.csv', col_types = cols()) %>% 
+     group_by(extent) %>% tally()
# A tibble: 3 × 2                 
  extent                      n
  <chr>                   <int>
1 aoi                      2119
2 aoi no sc                2119
3 shoreline contamination  2119
```

**Pull request merged**
