### PR TITLE
YUGO MODEL ACHEIVED!

### PR DESCRIPTION
**Pull request by steeleb**
Okay, no joke, this is the Yugo that almost falls apart, but it's a start!

This round of modeling took *significantly* longer than I thought it would (ahhhh science, you're so cool), but I deeply wanted to get this finished before the weekend so you could play with these data and maybe get to the point of preliminary analysis and I could play bikes and not think about how I'm holding you up.

# Caveats with the Yugo model 
The output is in the Drive at eePlumB_classification/quick_gradientTreeBoost_landsat_stack_v2023-05-05.csv.

1) The data have not been mosaic'd across mission-dates. This means there may be multiple rows of data for a given mission-date. These rows need to be aggregated (by sum, except area_ha, which is the total area of our AOI and is/should be static) before you move forward. There *shouldn't* be more than 2 rows per mission-date.
2) This form of summation is a straw dog to get things running. You may certainly have instances where the total area as summed across all classes (all columns are in square meters except area_ha) is greater than the total aoi area (area_ha column). This is due to overlapping path/rows. This will not be the case in future models I just couldn't get GEE to participate in reasonable requests this afternoon.
3) I have done ZERO sanity checks for this data. (As soon as it gets in the Drive, I'll confirm that it actually has data that looks sane.) 
4) Also, ZERO upstream data dismissal in this workflow nor playing with aggregating classes

Here are the __very fancy__ statistics for this model (gradient tree boost model on all band data):
basic_GBT_2023-05-05
Training n = 1404, Testing n = 346. Classes: 0 = clouds; 1 = openWater, 2 = lightNearShore, 3 = offShore, 4 = darkNearShore. 

Just for clarity/in case: this is read as for class 0 as determined by the model, the labelers assigned 93 points as class 0, 7 as class 1,  1 as class 2, 1 as class 3,  0 as class 4.

You'll notice I had to make some edits to the upstream script, too.

### CODE REVIEW

**Comment by steeleb** [comment]
And a few more tweaks so we can actually get dates in the export. #facepalm

**Comment by lindsayplatt** [comment]
I am enjoying following along with your commit messages 😆 Oh my have I been there!

**Comment by steeleb** [comment]
omg, these commits were truly how I was feeling. I'm glad you enjoyed them. In the moment I did not enjoy them, but in hindsight, they are quite funny.

**Comment by steeleb** [comment]
Also, now that I know there are data that were functional, I'm going to tag you in review here. Linking #26 to this script to close with merge, but making a few additional issues:

[Perform labeling on mosaic-ed date-mission images#49](https://github.com/rossyndicate/Superior-Plume-Bloom/issues/49)

Excited to hear about the preliminary modeling and the IGLAR. Let's plan to chat before my next bout with this project (likely when I get back from travels).

**Comment by steeleb** [comment]
@lindsayplatt, pinging you on this and the other PR here! :)

**Comment by lindsayplatt** [comment]
Huh, I approved and merged #50 then went to this one to review and it automatically merged along with the previous one. Perhaps because the commits were built off of one another? I'll review now anyways but that's why it was merged first!

**Review by lindsayplatt — COMMENTED** [review]
I've "reviewed" this by pulling down the data and working with it. I think I followed all of your guidance about needing to summarize by mission-date. I used the `classification` column to turn each of the other class columns into a value representing the percent of the area that *could* be classified (using the value in `classification`). Code is below. Based on this, I've got two thoughts:

1. I feel like the `classification` column already takes clouds into consideration because the % area for cloud cover has values > 100. Does that sound right?
2. There is a column in that data called `.geo` and it destroys my computers ability to do anything. I loaded in the raw CSV, deleted that column, and then saved a new file to continue to work. Can we eliminate that or save it differently somehow?

image

<details>
  <summary>Expand to see the code used to create the plot above (keeping here for future me)</summary>

```r
library(tidyverse)

# Drop the `.geo` column WHICH IS HUGE
# read_csv('quick_gradientTreeBoost_landsat_stack_v2023-05-06.csv') %>% 
#   select(-.geo) %>% 
#   write_csv('bsteele_pixel_counts_tabular.csv')

# date: date of Landsat image
# mission: mission that acquired landsat image
# Area_ha = total area of the AOI. This is static and in ha.
# Classification = total area within the aoi in that scene that there is image available (meters-squared)
# OSSed = total area within the aoi in that scene that is classified as offShoreSediment (meters-squared)
# Cloud = total area within the aoi in that scene area (classification) that has been classified as cloud (meters squared)
# dNSSed = total area within the aoi in that scene area (classification) that has been classified as darkNearShoreSediment (meters squared)
# openWater: total area within the aoi in that scene area (classification) that has been classified as openWater (meters squared)
# lightNSSed: total area within the aoi in that scene area (classification) that has been classified as lightNearShoreSediment (meters squared)

yugo_raw <- read_csv('bsteele_pixel_counts_tabular.csv')

# Summarize each class as % area of the aoi scene using `classification` column
# as the area because it represents what *could* have been classified.
pct_of_classifiable_aoi <- function(class_area, aoi_area_with_imagery) {
  (class_area / aoi_area_with_imagery) * 100
}
classification_cols <- c('cloud', 'OSSed', 'dNSSed', 'lightNSSed', 'openWater')
yugo_clean <- yugo_raw %>% 
  group_by(mission, date, area_ha) %>% 
  summarize(across(one_of(c(classification_cols, 'classification')), ~sum(.x, na.rm=T))) %>% 
  mutate(across(classification_cols, ~pct_of_classifiable_aoi(.x, classification), .names="pct_{.col}"))

yugo_clean_long <- yugo_clean %>% 
  select(mission, date, starts_with('pct_')) %>% 
  pivot_longer(starts_with('pct'), names_to = "class", 
               names_transform = ~gsub('pct_', '', .x),
               values_to = 'pct_of_classifiable_area')

# Timeseries of each of the class percents
ggplot(yugo_clean_long, aes(x=date, y=pct_of_classifiable_area, color = mission)) +
  geom_point(shape=1) +
  facet_grid(class ~ ., scales='free_y')
```

</details>

**Comment by steeleb** [comment]
You're such a rockstar!

Agreed that we need to dump the .geo column. I think I tried to do this, but it wouldn't export for some reason. I'll go back through and make sure that we can get rid of that so that the file isn't 5gb anymore. 

As for the cloud cover - that is so wonky! I'll look into this more in the next iteration. Thanks for performing a sanity check here.

**Pull request merged**
